USE final_ecommerce_project;

-- 11.1. Percentage of revenue generated by top 10% of customers

WITH CustomerRevenue AS(
		SELECT C.CustomerID,
				SUM(OD.Quantity * P.Price) AS Revenue
		 FROM customers C 
		 JOIN orders O ON O.CustomerID = C.CustomerID
		 JOIN orderdetails OD ON OD.OrderID = O.OrderID
		 JOIN products P ON P.ProductID = OD.ProductID
		 WHERE O.IsReturned = False
		 GROUP BY C.CustomerID
),
RankedCustomers AS(
		SELECT *,
				NTILE(10) OVER(ORDER BY Revenue DESC) AS RevenueBucket
		FROM CustomerRevenue
),
RevenueSummary AS(
		SELECT SUM(Revenue) AS TotalRevenue,
				SUM( CASE WHEN RevenueBucket = 1 THEN Revenue END ) AS Top10PercentRevenue
		FROM RankedCustomers
)
SELECT TotalRevenue, Top10PercentRevenue, 
		ROUND(
					(Top10PercentRevenue) * 100.0 / NULLIF( TotalRevenue, 0), 2
			  ) AS Top10PercentRevenueContribution
FROM RevenueSummary;

-- 11.2. Percentage of revenue generated by top 10 products

WITH ProductRevenue AS(
		SELECT P.ProductID,
				SUM(OD.Quantity * P.Price) AS Revenue
		FROM orders O 
        JOIN orderdetails OD ON OD.OrderID = O.OrderID
        JOIN products P ON P.ProductID = OD.ProductID
        WHERE O.IsReturned = False
        GROUP BY P.ProductID
),
RankedOrders AS (
		SELECT *,
				DENSE_RANK() OVER (ORDER BY Revenue DESC) AS RevenueRank
		FROM ProductRevenue
),
RevenueSummary AS(
		SELECT SUM(Revenue) AS TotalRevenue,
				SUM( CASE WHEN RevenueRank <= 10 THEN Revenue END) AS Top10ProductRevenue
		FROM RankedOrders
)
SELECT TotalRevenue, Top10ProductRevenue,
		ROUND(
				 (Top10ProductRevenue * 100.0) / (NULLIF(TotalRevenue,0)), 2
			  ) AS Top10PercentRevenueContribution
FROM RevenueSummary;

-- 11.3. Long-tail product contribution to total revenue

WITH ProductRevenue AS (
		SELECT P.ProductID, P.ProductName,
			   SUM(OD.Quantity * P.Price) AS Revenue
		FROM orders O
		JOIN orderdetails OD ON OD.OrderID = O.OrderID
		JOIN products P ON P.ProductID = OD.ProductID
		WHERE O.IsReturned = FALSE
		GROUP BY P.ProductID, P.ProductName
),
RevenueWithCumulative AS (
		SELECT *,
			   SUM(Revenue) OVER() AS TotalRevenue,
			   SUM(Revenue) OVER (ORDER BY Revenue DESC) AS CumulativeRevenue
		FROM ProductRevenue
)
SELECT 
    ROUND(
        (SUM(CASE WHEN CumulativeRevenue > (0.8 * TotalRevenue) THEN Revenue END) * 100.0) 
        / NULLIF(MAX(TotalRevenue), 0), 2
    ) AS LongTailRevenuePercent
FROM RevenueWithCumulative;

-- 11.4. Order concentration analysis (few large orders vs many small orders)

WITH OrderRevenue AS (
    SELECT 
        O.OrderID,
        SUM(OD.Quantity * P.Price) AS Revenue
    FROM orders O
    JOIN orderdetails OD ON OD.OrderID = O.OrderID
    JOIN products P ON P.ProductID = OD.ProductID
    WHERE O.IsReturned = False
    GROUP BY O.OrderID
),
RankedRevenue AS (
    SELECT 
        OrderID,
        Revenue,
        NTILE(10) OVER (ORDER BY Revenue DESC) AS RevenueRank
    FROM OrderRevenue
),
RevenueCategory AS (
    SELECT 
        Revenue,
        CASE 
            WHEN RevenueRank = 1 THEN 'High-value orders'
            WHEN RevenueRank BETWEEN 2 AND 5 THEN 'Medium-value orders'
            ELSE 'Low-value orders'
        END AS RevenueType
    FROM RankedRevenue
),
TotalRevenue AS (
    SELECT SUM(Revenue) AS OverAllRevenue
    FROM OrderRevenue
)
SELECT 
    RC.RevenueType,
    ROUND(
        (SUM(RC.Revenue) * 100.0) / NULLIF(MAX(TR.OverAllRevenue), 0),
        2
    ) AS RevenueContributionPercent
FROM RevenueCategory RC
CROSS JOIN TotalRevenue TR
GROUP BY RC.RevenueType
ORDER BY RevenueContributionPercent DESC;

-- 11.5. Revenue dependency on top categories

WITH CategoryRevenue AS(
		SELECT P.Category,
				SUM( OD.Quantity * P.Price) AS Revenue
		FROM orders O 
        JOIN orderdetails OD ON OD.OrderID = O.OrderID
        JOIN products P ON P.ProductID = OD.ProductID
        WHERE O.IsReturned = False
        GROUP BY P.Category
),
RankedCategories AS(
		SELECT *,
				NTILE(3) OVER(ORDER BY Revenue DESC) CategoryBucket,
                SUM(Revenue) OVER() AS TotalRevenue
		FROM CategoryRevenue
)
SELECT ROUND(
					(SUM(CASE WHEN CategoryBucket = 1 THEN Revenue END) * 100.0)/ NULLIF(MAX(TotalRevenue), 0), 2
			  ) AS TopCategoryRevenueDependencyPercent
FROM RankedCategories;
				
